# Generated by Django 4.2.7 on 2025-10-11 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CalculationHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alpha", models.FloatField()),
                ("h0_params", models.JSONField()),
                ("h1_params", models.JSONField()),
                ("threshold", models.FloatField()),
                ("power", models.FloatField()),
                ("gamma", models.FloatField(help_text="Randomization factor")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
