# Generated by Django 4.2.7 on 2025-11-20 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculationhistory',
            name='extra_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
