# Generated by Django 4.2.7 on 2025-11-20 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_calculationhistory_extra_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculationhistory',
            name='alpha',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
