# Generated by Django 4.2.7 on 2025-11-20 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0004_alter_calculationhistory_alpha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculationhistory',
            name='gamma',
            field=models.FloatField(blank=True, help_text='Randomization factor', null=True),
        ),
    ]
