# Generated by Django 4.2.7 on 2025-10-12 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theory", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={
                "ordering": ["order"],
                "verbose_name": "Статья",
                "verbose_name_plural": "Статьи",
            },
        ),
        migrations.RemoveField(
            model_name="article",
            name="content",
        ),
        migrations.AddField(
            model_name="article",
            name="content_html",
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name="article",
            name="content_md",
            field=models.TextField(
                default=1,
                help_text="Содержимое в формате Markdown",
                verbose_name="Содержимое (Markdown)",
            ),
            preserve_default=False,
        ),
    ]
