# Generated by Django 4.2.7 on 2025-10-12 15:29

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ("theory", "0002_alter_article_options_remove_article_content_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="content_rich",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True,
                help_text="Богатый текстовый редактор",
                verbose_name="Содержимое (Визуальный редактор)",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="content_md",
            field=models.TextField(
                blank=True,
                help_text="Содержимое в формате Markdown",
                verbose_name="Содержимое (Markdown)",
            ),
        ),
    ]
