# Generated by Django 4.2.7 on 2025-10-12 15:52

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ("theory", "0003_article_content_rich_alter_article_content_md"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="content_md",
        ),
        migrations.AlterField(
            model_name="article",
            name="content_rich",
            field=django_ckeditor_5.fields.CKEditor5Field(
                help_text="Содержимое статьи", verbose_name="Содержимое"
            ),
        ),
    ]
