# Generated by Django 4.2.7 on 2025-11-20 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theory', '0003_convert_to_markdown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content_md',
            field=models.TextField(help_text='Содержимое статьи в формате Markdown', verbose_name='Содержимое (Markdown)'),
        ),
    ]
