# Generated by Django 4.2.7 on 2025-10-11 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="answer",
            options={"verbose_name": "Ответ", "verbose_name_plural": "Ответы"},
        ),
        migrations.AlterModelOptions(
            name="question",
            options={"verbose_name": "Вопрос", "verbose_name_plural": "Вопросы"},
        ),
        migrations.AlterField(
            model_name="answer",
            name="is_correct",
            field=models.BooleanField(default=False, verbose_name="Правильный ответ"),
        ),
        migrations.AlterField(
            model_name="answer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="quiz.question",
                verbose_name="Вопрос",
            ),
        ),
        migrations.AlterField(
            model_name="answer",
            name="text",
            field=models.CharField(max_length=255, verbose_name="Текст ответа"),
        ),
        migrations.AlterField(
            model_name="question",
            name="explanation",
            field=models.TextField(
                blank=True,
                help_text="Пояснение к правильному ответу.",
                verbose_name="Пояснение",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="text",
            field=models.TextField(verbose_name="Текст вопроса"),
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Название теста"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "questions",
                    models.ManyToManyField(
                        related_name="quizzes",
                        to="quiz.question",
                        verbose_name="Вопросы",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тест",
                "verbose_name_plural": "Тесты",
            },
        ),
        migrations.AddField(
            model_name="quizresult",
            name="quiz",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="quiz.quiz"
            ),
            preserve_default=False,
        ),
    ]
